image:
- Visual Studio 2017

services:
  - mssql2017

install:
  - ps choco install make
  - set PATH=C:\ProgramData\chocolatey\lib\make\tools;%PATH%
  
build_script:
  - ps $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
  - ps [System.Environment]::GetEnvironmentVariable("Path","Machine")
  - make build

after_build:
  - ps $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
  - make database USERID=sa DBSERVER="(local)\SQL2017" DBNAME=master