image:
- Visual Studio 2017

services:
  - mssql2017

install:
  - ps: |
        function AddToPath([string] $path) {
  
          $key = "PATH"
          $currentPath = [Environment]::GetEnvironmentVariable($key, "Machine")

          if($currentPath.Contains($path)) {
            Write-Warning "'$path' already exists in $key, nothing added"
            return
          }  
  
          Write-Host "Adding '$path' to $key"
          if($path.EndsWith(";")) {
            $newPath = $currentPath + "$path;"
          }else {
            $newPath = $currentPath + ";$path;"
          }
          [Environment]::SetEnvironmentVariable($key, $newPath, "Machine")
        }
  - ps: choco install make
  - ps: AddToPath "C:\ProgramData\chocolatey\lib\make\tools\bin"
  
before_build:
  - cmd: make --version
  - cmd: make database DBSERVER="(local)\SQL2017" DBUSER=migration-runner DBPASSWORD="Passw0rd12!"
  

build_script:
  - cmd: make build
  - cmd: make package CONFIGURATION=Release BUILD_NUMBER=%APPVEYOR_BUILD_NUMBER%

before_test:
  - ps: [Environment]::SetEnvironmentVariable("identityConnection", "Server=(local)\SQL2017;Database=identity;User ID=migration-runner;Password=Passw0rd12!", "Machine")
  - ps: RefreshEnv

test:
  - cmd: make test

after_test:
  - cmd: make cleanup-db DBSERVER="(local)\SQL2017" DBUSER=migration-runner

artifacts:
  - path: '**\*.nupkg' # push all *.nupkg files in build directory recursively