image:
- Visual Studio 2017

services:
  - mssql2017

install:
  - ps choco install make
  - set PATH=C:\ProgramData\chocolatey\lib\make\tools;%PATH%
  - $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
  
before_build:
- nuget restore

after_test:
-  make database USERID=sa DBSERVER="(local)\SQL2017" DBNAME=master