image:
- Visual Studio 2017

services:
  - mssql2017

install:
  - ps: |
        function AddToPath([string] $path) {
  
          $key = "PATH"
          $currentPath = [Environment]::GetEnvironmentVariable($key, "Machine")

          if($currentPath.Contains($path)) {
            Write-Warning "'$path' already exists in $key, nothing added"
            return
          }  
  
          Write-Host "Adding '$path' to $key"
          if($path.EndsWith(";")) {
            $newPath = $currentPath + "$path;"
          }else {
            $newPath = $currentPath + ";$path;"
          }
          [Environment]::SetEnvironmentVariable($key, $newPath, "Machine")
        }
  - ps choco install make
  - ps AddToPath "C:\ProgramData\chocolatey\lib\make\tools\bin"
  - ps cp c:\MinGW\bin\mingw32-make.exe c:\MinGW\bin\make.exe
  - ps AddToPath "c:\MinGW\bin"

before_build:
  - make --version

build_script:
  - make build

after_build:
  - ps $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
  - make database USERID=sa DBSERVER="(local)\SQL2017" DBNAME=master