image:
- Visual Studio 2017

services:
  - mssql2017

install:
  - ps choco install make --debug
  - set PATH=C:\ProgramData\chocolatey\bin;%PATH%

before_build:
  - make --version

build_script:
  - make build

after_build:
  - ps $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
  - make database USERID=sa DBSERVER="(local)\SQL2017" DBNAME=master