image:
- Visual Studio 2017

services:
  - mssql2017

install:
  - ps choco install make
  - Invoke-WebRequest -Uri "ftp://ftp.equation.com/make/64/make.exe" -OutFile C:\ProgramData\chocolatey\bin\make.exe
  - set PATH=C:\ProgramData\chocolatey\bin;%PATH%

build_script:
  - make build

after_build:
  - ps $env:Path = [System.Environment]::GetEnvironmentVariable("Path","Machine")
  - make database USERID=sa DBSERVER="(local)\SQL2017" DBNAME=master